"""empty message

Revision ID: 261f1b54758c
Revises: 8dd8865dd18a
Create Date: 2019-09-26 01:06:02.904789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261f1b54758c'
down_revision = '8dd8865dd18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
